#!/bin/bash

export MY_NAME=$(basename "$0")
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/_hooks.sh"

FOR=Rubocop     run_program bundle exec rubocop --color --parallel
FOR=ESLint      run_program yarn eslint --color .
FOR=TypeScript  run_program yarn tsc-full
FOR=HAML-Lint   run_program bundle exec haml-lint --color --parallel
FOR=Stylelint   run_program yarn stylelint-all --color
FOR=I18n-Health run_program bundle exec i18n-tasks health
FOR=RSpec       run_program bundle exec rspec --force-color --format documentation
